name: Environment Variables
on: [workflow_dispatch]

jobs:
  name: Run Script
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v1
    - name: Script
      run: ./script.ps1
      shell: pwsh
      env:
        MyVariable: 'Hello Mendel'
