name: Inline commands
on: [workflow_dispatch]

jobs:
  build:
    name: Run Script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Script
        run: Write-Host 'Hi Mendel!!! This is inline command'
        shell: pwsh
