name: Install Modules Power Shell
on: [workflow_dispatch]

jobs:
  build:
    name: Run Script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Script
        run: .\script.ps1 -Parameter1 'Parameter Test'
        shell: pwsh
